language: java

services:
  - docker

before_install:
  - docker run maven:3.3-jdk-8
  - docker ps -a

#jobs:
#  include:
#    - stage: test
#      script: mvn clean test -Dtest=com.clarolab.selenium.SeleniumTest#passSeleTest
#
#addons:
#  artifacts:
#    paths:
#    - ~/repo/target/surefire-reports/testng-results.xml