language: java

jobs:
  include:
    - stage: test1
      script: mvn clean test -Dtest=com.clarolab.selenium.SeleniumTest

addons:
  artifacts:
    paths:
    - ~/repo/target/surefire-reports/testng-results.xml